FROM ubuntu:15.04
ENV TERM xterm
RUN apt-get -y update

RUN apt-get install -y curl
RUN apt-get install -y iputils-ping
RUN apt-get install -y nano
RUN apt-get install -y bzip2
RUN apt-get install -y git

RUN mkdir /data

